seed: 2022
reproducibility: False
glove_embedding_path: './recbole_trm/dataset/glove.840B.300d.txt'
news_path: './recbole_trm/dataset/news.tsv'
behavior_train_path: './recbole_trm/dataset/behaviors.tsv'
processed_npbehavior_train_path: './recbole_trm/dataset/npbehaviors.tsv'
behavior_test_path: './recbole_trm/dataset/behaviors.tsv'
saved_path: './recbole_trm/saved/'
batch_size: 32
learning_rate: 0.0001
epochs: 10
log_steps: 100
num_workers: 4
freeze_embedding: False
enable_gpu: True
n_gpu: 0
npratio: 1
embedding_size: 10
dropout_prob: 0.1
filter_num: 3
num_words_title: 20
word_embedding_dim: 300
use_category: True
use_subcategory: True
num_attention_heads: 20
news_dim: 400
news_query_vector_dim: 200
category_emb_dim: 100
user_query_vector_dim: 200
user_log_length: 50
user_log_mask: True
